# =========================
# SERVICES
# =========================
services:
  # =========================
  # ADMINISTRATION
  # =========================
  ### TRAEFIK ###
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http"
      - "--certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/acme.json"
    environment:
      - DUCKDNS_TOKEN=${DUCKDNS_TOKEN}
    ports:
      - "80:80"
      - "443:443"
      - "${TRAEFIK_DASHBOARD_PORT}:${TRAEFIK_DASHBOARD_PORT}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${HOME_SERVER_PATH}/traefik/acme.json:/acme.json"
      - "${HOME_SERVER_PATH}/traefik/certs:/certs:ro"
      - "${HOME_SERVER_PATH}/traefik/traefik.yml:/traefik.yml:ro"
    networks:
      - proxy
    labels:
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-http.middlewares=redirect-to-https"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik-http.rule=Host(`traefik.${DUCKDNS_DOMAIN}`)"
      - "traefik.http.routers.traefik-http.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DUCKDNS_DOMAIN}`)"
      - "traefik.http.routers.traefik.entrypoints=https"
      - "traefik.http.services.traefik.loadbalancer.server.port=${TRAEFIK_DASHBOARD_PORT}"

  ### PORTAINER ###
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - proxy
    labels:
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.enable=true"
      - "traefik.http.routers.portainer-http.rule=Host(`portainer.${DUCKDNS_DOMAIN}`)"
      - "traefik.http.routers.portainer-http.entrypoints=http"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${DUCKDNS_DOMAIN}`)"
      - "traefik.http.routers.portainer.entrypoints=https"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"
      - "traefik.http.services.portainer.loadbalancer.server.port=${PORTAINER_PORT}"

  ### DUCKDNS ###
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SUBDOMAINS=${DUCKDNS_SUBDOMAINS}
      - TOKEN=${DUCKDNS_TOKEN}
    volumes:
      - ${HOME_SERVER_PATH}/duckdns/config:/config
    restart: unless-stopped

  ### ADGUARD ###
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    volumes:
      - ${HOME_SERVER_PATH}/adguard/workdir:/opt/adguardhome/work
      - ${HOME_SERVER_PATH}/adguard/conf:/opt/adguardhome/conf
    networks:
      - proxy
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "${ADGUARD_PORT}:${ADGUARD_PORT}/tcp"
    expose:
      - "3000"
    labels:
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.enable=true"
      - "traefik.http.routers.adguard-http.rule=Host(`adguard.${DUCKDNS_DOMAIN}`)"
      - "traefik.http.routers.adguard-http.entrypoints=http"
      - "traefik.http.services.adguard.loadbalancer.server.port=${ADGUARD_PORT}"

# =========================
# MEDIA
# =========================
  ### NAVIDROME - Music Platform ###
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    environment:
      ND_SCANINTERVAL: ${ND_SCANINTERVAL}
      ND_LOGLEVEL: info
      ND_PREFERFFMPEG: true
    volumes:
      - "${STORAGE_PATH}/navidrome/data:/data"
      - "${STORAGE_PATH}/music:/music:ro"
    networks:
      - proxy
    labels:
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.enable=true"
      - "traefik.http.routers.navidrome-http.rule=Host(`navidrome.${DUCKDNS_DOMAIN}`)"
      - "traefik.http.routers.navidrome-http.entrypoints=http"
      - "traefik.http.routers.navidrome-http.middlewares=redirect-to-https"
      - "traefik.http.routers.navidrome.rule=Host(`navidrome.${DUCKDNS_DOMAIN}`)"
      - "traefik.http.routers.navidrome.entrypoints=https"
      - "traefik.http.routers.navidrome.tls=true"
      - "traefik.http.routers.navidrome.tls.certresolver=letsencrypt"
      - "traefik.http.services.navidrome.loadbalancer.server.port=${NAVIDROME_PORT}"

  ### JELLYFIN - Media Server ###
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - ${JELLYFIN_PORT_TCP}:${JELLYFIN_PORT_TCP}/tcp
      - ${JELLYFIN_PORT_UDP}:${JELLYFIN_PORT_UDP}/udp
    volumes:
      - ${HOME_SERVER_PATH}/jellyfin/config:/config
      - ${HOME_SERVER_PATH}/jellyfin/cache:/cache
      - type: bind
        source: ${STORAGE_PATH}/media
        target: /media
      - type: bind
        source: ${HOME_SERVER_PATH}/jellyfin/fonts
        target: ${HOME_SERVER_PATH}/jellyfin/fonts/custom
        read_only: true
    networks:
      - proxy
    labels:
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin-http.rule=Host(`jellyfin.${DUCKDNS_DOMAIN}`)"
      - "traefik.http.routers.jellyfin-http.entrypoints=http"
      - "traefik.http.routers.jellyfin-http.middlewares=redirect-to-https"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DUCKDNS_DOMAIN}`)"
      - "traefik.http.routers.jellyfin.entrypoints=https"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.routers.jellyfin.tls.certresolver=letsencrypt"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=${JELLYFIN_PORT_TCP}"

  ### FEISHIN - Music Streaming ###
  feishin:
    container_name: feishin
    image: ghcr.io/jeffvli/feishin:latest
    restart: unless-stopped
    environment:
      - SERVER_NAME=${FS_SERVER_NAME}
      - SERVER_LOCK=true
      - SERVER_TYPE=${FS_SERVER_TYPE}
      - SERVER_URL=https://navidrome.${DUCKDNS_DOMAIN}
      - LEGACY_AUTHENTICATION=false
      - ANALYTICS_DISABLED=false
    ports:
      - ${FEISHIN_PORT}:${FEISHIN_PORT}
    networks:
      - proxy
    labels:
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.enable=true"
      - "traefik.http.routers.feishin-http.rule=Host(`feishin.${DUCKDNS_DOMAIN}`)"
      - "traefik.http.routers.feishin-http.entrypoints=http"
      - "traefik.http.routers.feishin-http.middlewares=redirect-to-https"
      - "traefik.http.routers.feishin.rule=Host(`feishin.${DUCKDNS_DOMAIN}`)"
      - "traefik.http.routers.feishin.entrypoints=https"
      - "traefik.http.routers.feishin.tls=true"
      - "traefik.http.routers.feishin.tls.certresolver=letsencrypt"
      - "traefik.http.services.feishin.loadbalancer.server.port=${FEISHIN_PORT}"

# =========================
# PRODUCTIVITY
# =========================
  ### FILEBROWSER ###
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: always
    volumes:
      - ${HOME_SERVER_PATH}/filebrowser/config:/config
      - /home/yanneckbuelow:/srv
    networks:
      - proxy
    labels:
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser-http.rule=Host(`files.${DUCKDNS_DOMAIN}`)"
      - "traefik.http.routers.filebrowser-http.entrypoints=http"
      - "traefik.http.routers.filebrowser-http.middlewares=redirect-to-https"
      - "traefik.http.routers.filebrowser.rule=Host(`files.${DUCKDNS_DOMAIN}`)"
      - "traefik.http.routers.filebrowser.entrypoints=https"
      - "traefik.http.routers.filebrowser.tls=true"
      - "traefik.http.routers.filebrowser.tls.certresolver=letsencrypt"
      - "traefik.http.services.filebrowser.loadbalancer.server.port=${FILEBROWSER_PORT}"

  ### DOCMOST - Documentation Management ###
  docmost:
    image: docmost/docmost:latest
    depends_on:
      - docmost-db
      - docmost-redis
    environment:
      APP_URL: "https://docmost.${DUCKDNS_DOMAIN}"
      APP_SECRET: "${DOCMOST_SECRET}"
      DATABASE_URL: "${DOCMOST_DB_URL}"
      REDIS_URL: "${DOCMOST_REDIS_URL}"
    restart: unless-stopped
    volumes:
      - docmost_data:/app/data/storage
    networks:
      - proxy
    labels:
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.enable=true"
      - "traefik.http.routers.docmost-http.rule=Host(`docmost.${DUCKDNS_DOMAIN}`)"
      - "traefik.http.routers.docmost-http.entrypoints=http"
      - "traefik.http.routers.docmost-http.middlewares=redirect-to-https"
      - "traefik.http.routers.docmost.rule=Host(`docmost.${DUCKDNS_DOMAIN}`)"
      - "traefik.http.routers.docmost.entrypoints=https"
      - "traefik.http.routers.docmost.tls=true"
      - "traefik.http.routers.docmost.tls.certresolver=letsencrypt"
      - "traefik.http.services.docmost.loadbalancer.server.port=${DOCMOST_PORT}"

  docmost-db:
    networks:
      - internal
    image: postgres:18
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    restart: unless-stopped
    volumes:
      - docmost_db_data:/var/lib/postgresql/data

  docmost-redis:
    image: redis:8
    command: ["redis-server", "--appendonly", "yes", "--maxmemory-policy", "noeviction"]
    restart: unless-stopped
    volumes:
      - docmost_redis_data:/data"

# =========================
# MANAGEMENT
# =========================
  ### HOMARR ###
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - /home/yanneckbuelow/home-server/homarr/appdata:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=${HOMARR_SECRET_ENCRYPT_KEY}
    ports:
      - '${HOMARR_PORT}:${HOMARR_PORT}'
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      # HTTP-Router (Port 80) redirect
      - "traefik.http.routers.homarr-http.rule=Host(`home.${DUCKDNS_DOMAIN}`)"
      - "traefik.http.routers.homarr-http.entrypoints=http"
      - "traefik.http.routers.homarr-http.middlewares=https-redirect"
      # HTTPS-Router (Port 443) app
      - "traefik.http.routers.homarr.rule=Host(`home.${DUCKDNS_DOMAIN}`)"
      - "traefik.http.routers.homarr.entrypoints=https"
      - "traefik.http.routers.homarr.tls=true"
      - "traefik.http.routers.homarr.tls.certresolver=letsencrypt"
      - "traefik.http.services.homarr.loadbalancer.server.port=${HOMARR_PORT}"
    networks:
      - proxy

  ### BEETS - Music Management ###
  beets:
    image: lscr.io/linuxserver/beets:latest
    container_name: beets
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${HOME_SERVER_PATH}/beets/config:/config
      - ${STORAGE_PATH}/music:/music
      - ${STORAGE_PATH}/beets/downloads:/downloads
      - ${STORAGE_PATH}/multimedia/Musik/Musik/SpotifyCollection/DOWNLOADS:/spotifycollection
    ports:
      - ${BEETS_PORT}:${BEETS_PORT}
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.enable=true"
      - "traefik.http.routers.beets-http.rule=Host(`beets.${DUCKDNS_DOMAIN}`)"
      - "traefik.http.routers.beets-http.entrypoints=http"
      - "traefik.http.routers.beets-http.middlewares=redirect-to-https"
      - "traefik.http.routers.beets.rule=Host(`beets.${DUCKDNS_DOMAIN}`)"
      - "traefik.http.routers.beets.entrypoints=https"
      - "traefik.http.routers.beets.tls=true"
      - "traefik.http.routers.beets.tls.certresolver=letsencrypt"
      - "traefik.http.services.beets.loadbalancer.server.port=${BEETS_PORT}"

# =========================
# VOLUMES AND NETWORKS
# =========================
volumes:
  portainer_data:
  docmost_data:
  docmost_db_data:
  docmost_redis_data:

networks:
  proxy:
    external: true
  internal:
    driver: bridge