#temporary disable spotify, beatport, lyrics
plugins: musicbrainz deezer discogs inline fromfilename fetchart embedart convert scrub replaygain lastgenre chroma web permissions duplicates
directory: /music
library: /config/musiclibrary.blb
art_filename: albumart
threaded: yes
original_date: no
per_disc_numbering: yes

convert:
    auto: no
    ffmpeg: /usr/bin/ffmpeg
    opts: -ab 320k -ac 2 -ar 48000
    max_bitrate: 320
    threads: 1

paths:
    default: $albumartist/$album%aunique{}/$disc/$track - $title
    singleton: Non-Album/$artist - $title
    comp: Compilations/$album%aunique{}/$disc/$track - $title
    albumtype_soundtrack: Soundtracks/$album/$disc/$track $title

import:
    write: yes
    copy: no
    move: yes
    resume: ask
    incremental: yes
    quiet: yes
    quiet_fallback: asis
    timid: no
    log: /config/beet.log

match:
    strong_rec_thresh: 0.6

lastgenre:
    auto: yes
    source: album

embedart:
    auto: yes

fetchart:
    auto: yes

replaygain:
    auto: no
    command: mp3gain

scrub:
    auto: yes

replace:
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '[\xE8-\xEB]': e
    '[\xEC-\xEF]': i
    '[\xE2-\xE6]': a
    '[\xF2-\xF6]': o
    '[\xF8]': o
    '\.$': _
    '\s+$': ''

web:
    host: 0.0.0.0
    port: 8337

musicbrainz:
    data_source_mismatch_penalty: 0.3

discogs:
    apikey: <key>
    apisecret: <secret>
    user_token: <token>
    index_tracks: no
    append_style_genre: no
    separator: ', '
    strip_disambiguation: yes
    featured_string: Feat.
    anv:
        artist_credit: yes
        artist: no
        album_artist: no
    data_source_mismatch_penalty: 0.8
    search_limit: 5

deezer:
    data_source_mismatch_penalty: 0.6
    search_limit: 5

spotify:
    client_id: <id>
    client_secret: <secret>
    tokenfile: spotify_token.json
    data_source_mismatch_penalty: 0.4
    search_limit: 5

permissions:
    file: 644
    dir: 755

lyrics:
  auto: yes
  sources: [lrclib, google, genius]
  force: no
